In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(0)

# Define the number of samples
num_samples = 10000

# Simulate academic performance (GPA) on a 5.0 scale with 2 decimal places
mean_gpa = 3.0
std_dev_gpa = 0.5
gpa = np.random.normal(mean_gpa, std_dev_gpa, num_samples)
gpa = np.clip(gpa, 1.0, 5.0)  # Clip GPA values to be within a 1.0-5.0 range
gpa = np.round(gpa, 2)  # Round GPA values to two decimal places

# Simulate the binary target variable (1 for success, 0 for failure)
success_rate = 0.6  # Adjust this to set the success rate
success = np.random.choice([1, 0], num_samples, p=[success_rate, 1 - success_rate])

# Simulate additional features
education_levels = np.random.choice(['High School', 'Bachelors', 'Masters', 'PhD'], num_samples)
test_score = np.random.randint(0, 101, num_samples)  # Simulate test scores on a 0-100 scale
num_programming_languages = np.random.randint(0, 6, num_samples)  # Number of programming languages known
internship_type = np.random.choice(['Backend', 'Frontend', 'Machine Learning'], num_samples)  # Type of internship
farm_experience = np.random.randint(0, 11, num_samples)  # Years of farm-related experience
research_publications = np.random.randint(0, 6, num_samples)  # Number of research publications

# Change "Geographic_Region" to "Continent"
continent = np.random.choice(['North America', 'South America', 'Europe', 'Asia', 'Africa', 'Australia'], num_samples)

# Create a DataFrame to store the data
data = pd.DataFrame({
    'GPA': gpa,
    'Skills': num_programming_languages,
    'Internship_Success': success,
    'Education_Level': education_levels,
    'Test_Score': test_score,
    'Continent': continent,
    'Internship_Type': internship_type,
    'Farm_Experience': farm_experience,
    'Research_Publications': research_publications
})

# Save the dataset to a CSV file
data.to_csv('climdes_intern_dataset.csv', index=False)

In [2]:
import pandas as pd

# Define feature descriptions
feature_descriptions = {
    'Feature Name': [
        'GPA',
        'Skills',
        'Internship_Success',
        'Education_Level',
        'Test_Score',
        'Continent',
        'Internship_Type',
        'Farm_Experience',
        'Research_Publications'
    ],
    'Description': [
        'Grade Point Average on a 5.0 scale',
        'Number of programming languages known',
        'Binary target variable (1 for success, 0 for failure)',
        'Education level of the applicant (High School, Bachelors, Masters, PhD)',
        'Test score on a scale of 0-100',
        'Continent of the applicant',
        'Type of internship (Backend, Frontend, Machine Learning)',
        'Years of farm-related experience',
        'Number of research publications authored'
    ]
}

# Create a DataFrame for feature descriptions
data_description = pd.DataFrame(feature_descriptions)

# Save the data description to a CSV file
data_description.to_csv('data_description.csv', index=False)

In [3]:
data.head()

,GPA,Skills,Internship_Success,Education_Level,Test_Score,Continent,Internship_Type,Farm_Experience,Research_Publications
0,3.88,5,1,High School,66,South America,Frontend,9,4
1,3.20,0,1,High School,22,North America,Backend,3,2
2,3.49,2,1,Masters,65,Asia,Backend,5,5
3,4.12,1,0,High School,69,North America,Backend,7,2
4,3.93,4,1,Bachelors,53,Asia,Backend,2,1